name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    # from "use a default shell" here: https://github.com/conda-incubator/setup-miniconda
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yaml
        miniforge-variant: Mambaforge
        use-mamba: true
        
    - name: Create an installer
      run: |
        pyinstaller viirsbounds/viirsbounds.py

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: viirsbounds
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/*
        if-no-files-found: error
        retention-days: 0
